---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: lblod/delta-producer-publication-graph-maintainer
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - master
---
kind: pipeline
type: docker
name: release
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/delta-producer-publication-graph-maintainer
    dry_run: true
    purge: true
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: lblod/delta-producer-publication-graph-maintainer
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: NgJjT88j+VZWaG+tjgXyR0JVKxqaQOC6Dq6bFAi3nTUcehtNzywe5g==
---
kind: secret
name: docker_password
data: d85CLhyYim5yMhUstyDcdG9gt0eNv5rOtCvJ4P0SUgJSHwQ9giFC6vC9kxNktka317+3i1hWFkcKngXK/D4ABQ==
---
kind: signature
hmac: 2745b4b120536e9ad72c5e953a3df627fbc603833b0d1d6cfe661d6b00807bfa

...
